### ISSUE TITLE
Disable Metrics and Log Exporters

### ISSUE THREAD

**Issue by mmanciop** [lumigo-io/opentelemetry-java-distro#24]
Lumigo SaaS does not currently offer a `/v1/metrics` endpoint, so the default metrics exporter must be disable, or flood the logs of the hosting app with:

```
[otel.javaagent 2023-03-24 12:59:52:628 +0000] [OkHttp https://ga-otlp.lumigo-tracer-edge.golumigo.com/...] WARN io.opentelemetry.exporter.internal.okhttp.OkHttpExporter - Failed to export metrics. Server responded with HTTP status code 404. Error message: Unable to parse response body, HTTP status message: Not Found
```

**Comment by AlmogBaku** [comment]
Are you sure?

My intuition was to send them anyway; at some point, I expect that we'll support it...
Maybe we should look for a way to silence these kinds of warnings?
